### Numpy basics

1\. Find the row, column and overall means for the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [56]:
import numpy as np
m=np.arange(12).reshape((3,4))
print(m)
print(f'The mean of all the elements of the matrix is {m.mean()}')

for i,mean in enumerate(m.mean(axis=0)):
    print(f'The column {i} mean is {mean}')

for i,m in enumerate(m.mean(axis=1)):
    print(f'The row {i} mean is {m}')


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
The mean of all the elements of the matrix is 5.5
The column 0 mean is 4.0
The column 1 mean is 5.0
The column 2 mean is 6.0
The column 3 mean is 7.0
The row 0 mean is 1.5
The row 1 mean is 5.5
The row 2 mean is 9.5


2\. Find the outer product of the following two vecotrs

```python
u = np.array([1,3,5,7])
v = np.array([2,4,6,8])
```

Do this in the following ways:

   * Using the function outer in numpy
   * Using a nested for loop or list comprehension
   * Using numpy broadcasting operatoins


In [77]:
u = np.array([1,3,5,7])
v = np.array([2,4,6,8])
print(f'The outer product by the outer funciton is \n {np.outer(u,v)}')
print(f'The outer product by list comprehension is \n {np.array([[i*j for i in v] for j in u])}')
print(f'The outer product using broadcasting operations is \n {np.array([v*u[i] for i in range(len(v))])}')

The outer product by the outer funciton is 
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]
The outer product by list comprehension is 
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]
The outer product using broadcasting operations is 
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


3\. Create a 10 by 6 matrix of random uniform numbers. Set all rows with any entry less than 0.1 to be zero

Hint: Use the following numpy functions - np.random.random, np.any as well as Boolean indexing and the axis argument.

In [163]:
matrix=np.random.rand(10,6)
print(matrix)
mask=np.any(matrix<0.1,axis=1)
print(mask)
matrix[mask]=0
print(matrix)

[[0.86930399 0.55536666 0.70282314 0.71865416 0.32287966 0.55744467]
 [0.18267119 0.1150757  0.75588588 0.54574445 0.65366026 0.23710044]
 [0.08674042 0.5007618  0.62877878 0.17828753 0.85416237 0.47378332]
 [0.04417254 0.07597405 0.50078428 0.18587871 0.52740377 0.63568558]
 [0.90028968 0.35202076 0.30074999 0.31019003 0.53340642 0.85921142]
 [0.81464219 0.65114563 0.16999939 0.85567486 0.51860649 0.08643431]
 [0.94223252 0.41046335 0.00310791 0.06492422 0.8218562  0.68439493]
 [0.7066302  0.52812508 0.77621788 0.73820455 0.67982475 0.35194635]
 [0.36584182 0.22473597 0.44491527 0.25280848 0.89211323 0.3787114 ]
 [0.98354715 0.86969262 0.37662478 0.73277304 0.5979535  0.61920681]]
[False False  True  True False  True  True False False False]
[[0.86930399 0.55536666 0.70282314 0.71865416 0.32287966 0.55744467]
 [0.18267119 0.1150757  0.75588588 0.54574445 0.65366026 0.23710044]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.   

4\. Use np.linspace to create an array of 100 numbers between 0 and 2π (includsive).

  * Extract every 10th element using slice notation
  * Reverse the array using slice notation
  * Extract elements where the absolute difference between the sine and cosine functions evaluated at that element is less than 0.1
  * Make a plot showing the sin and cos functions and indicate where they are close

5\. Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anto-diagonal (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagnoal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

6\. Use broadcasting to create a grid of distances

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles
The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Construct a 2D grid of distances among each city along Route 66
  * Convert that in km (those savages...)

7\. Prime numbers sieve: compute the prime numbers in the 0-N (N=99 to start with) range with a sieve (mask).
  * Constract a shape (100,) boolean array, the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (timeit); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

**N.B. the following exercises are meant to be solved only if you are familiar with the numpy random library. If not you can skip them (postponed for one of the next exercise sessions)**


8\. Diffusion using random walk

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of a random walker after a given amount of time. 
To do that, let's simulate many walkers and create a 2D array with each walker as a raw and the actual time evolution as columns

  * Take 1000 walkers and let them walk for 200 steps
  * Use randint to create a 2D array of size walkers x steps with values -1 or 1
  * Build the actual walking distances for each walker (i.e. another 2D array "summing on each raw")
  * Take the square of that 2D array (elementwise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * Plot the average distances (sqrt(distance\*\*2)) as a function of time (step)
  
Did you get what you expected?

9\. Analyze a data file 
  * Download the population of hares, lynxes and carrots at the beginning of the last century.
    ```python
    ! wget https://www.dropbox.com/s/3vigxoqayo389uc/populations.txt
    ```

  * Check the content by looking within the file
  * Load the data (use an appropriate numpy method) into a 2D array
  * Create arrays out of the columns, the arrays being (in order): *year*, *hares*, *lynxes*, *carrots* 
  * Plot the 3 populations over the years
  * Compute the main statistical properties of the dataset (mean, std, correlations, etc.)
  * Which species has the highest population each year?

Do you feel there is some evident correlation here? [Studies](https://www.enr.gov.nt.ca/en/services/lynx/lynx-snowshoe-hare-cycle) tend to believe so.